### PR TITLE
Mobile menu

### PR DESCRIPTION
**Pull request by mrkamin**
What does this PR do?
This PR is raised to submit for code review in Microvers dashboard of Mohammad Rafi Amin.

Description of the task to be completed 👎
 - Add the HTML for the structure.
 - Add the CSS file for the styling.
 - Use the linter tool that analyzes my source code to flag programming errors, bugs, stylistic errors, and suspicious constructs.
 - use JS structures 
 -  💯
 - Use Figma a collaborative UI design tool built in the browser.
 - Use Flexbox a layout tool in CSS that helps you easily position HTML elements on the page.
 - This PR is raised to use GitHub pages which allows you to host (deploy) a webpage from your repository, for more information about how to use GitHub pages [Read here](https://www.w3schools.com/git/git_remote_pages.asp?remote=github) 🤩 if you want to watch a video about how to use GitHub pages instead of reading [Click here](https://www.youtube.com/watch?v=QyFcl_Fba-k&t=251s) ☺️.
 This is my portfolio hosted on GitHub pages, so if you want to check my portfolio online, please 😊 [Click here](https://mrkamin.github.io/)
How should it be tested
Clone the repository

git clone git@github.com:mrkamin/mrkamin.github.io.git
Navigate to the folder

cd portfolio
Checkout the branch

git checkout github_pages
Thanks for reviewing my PR 😊

### CODE REVIEW

**Comment by mrkamin** [comment]
Add JS structure for mobile menu in my portfolio

**Review by FrederickMih — APPROVED** [review]
Hi @mrkamin , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- Descriptive PR :heavy_check_mark: 
- Linters checks are OK :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@FrederickMih,
thanks for your good and valuable feedback and the approval.

**Comment by mrkamin** [comment]
solved linters errors

**Review by ha-manel — APPROVED** [review]
# STATUS: APPROVED ✅
## Hi @mrkamin 👋

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**

 

## Highlights:
* Well written PR description ✔️ 
* All tests passed ✔️ 
* Mobile menu is functioning properly ✔️ 


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@ha-manel,
thanks for your good and valuable feedback.

**Pull request merged**
